import type { Project } from './types'

export const projects: Project[] = [
  {
    slug: 'zetlar',
    name: 'Zetlar',
    icon: 'zetlar',
    accent: 'sage',
    kind: 'Hackathon',
    event: 'SwissHacks 2026 · Ripple',
    award: '🥇 1st overall + Ripple Challenge',
    team: 'Team Unicorn',
    teamPhoto: '/photos/team-zetlar.jpg',
    screenshot: '/photos/shot-zetlar.png',
    tagline: 'Get Mexican exporters paid today — settled on-chain.',
    description:
      'Mexican SMBs that export to the US wait 30–90 days to get paid, then lose ~3% converting dollars to pesos. Zetlar lets an exporter upload a US invoice and draw a 95% advance instantly, originated on the XRP Ledger, with USD→MXN swapped through an on-chain AMM at ~0.5%. Won first place overall out of 2000+ applicants.',
    tags: ['React', 'Django', 'XRPL', 'On-chain AMM', 'TypeScript'],
    links: [{ kind: 'live', label: 'Live site', url: 'https://zetlar.vercel.app' }],
  },
  {
    slug: 'ground-truth',
    name: 'Ground Truth',
    icon: 'groundtruth',
    accent: 'rose',
    kind: 'Hackathon',
    event: 'START Hack Zürich 2026 · SIX',
    award: '🎖️ Top 7 + Honorable Mention',
    team: 'Team Unicorn',
    teamPhoto: '/photos/team-ground-truth.jpg',
    screenshot: '/photos/shot-ground-truth.png',
    tagline: 'A company brain with answers you can defend.',
    description:
      "Enterprise knowledge is scattered across wikis, Slack, Jira and regulations, where it goes stale and conflicts. Ground Truth ingests it into a knowledge graph, enforces each user's access rights before ranking, resolves contradictions by authority and recency, and cites every claim so a human can verify it. Built for SIX; the core answer path is fully deterministic and works offline.",
    tags: ['React', 'Django', 'Claude', 'Knowledge graph', 'Embeddings'],
    links: [],
  },
  {
    slug: 'epaflow',
    name: 'epaFlow',
    icon: 'epaflow',
    accent: 'plum',
    kind: 'Hackathon',
    event: 'START Hack 2026 · ePA-CC',
    award: '🏆 Case Winner (Top 7 / 176)',
    team: 'Team Unicorn',
    teamPhoto: '/photos/team-epaflow.jpg',
    screenshot: '/photos/shot-epaflow.png',
    tagline: 'Turns messy medical data into clean, structured records.',
    description:
      'Every clinic speaks a different data dialect — CSVs, Excel dumps and text-only PDFs with mismatched headers. epaFlow runs a six-stage pipeline (ingest → detect → map → normalize → flag → review) that fingerprints each file, maps and normalizes every field, and flags rows for human review before export. It runs fully offline with an optional local LLM, so no clinical data ever leaves the machine.',
    tags: ['React', 'Django', 'Local LLM', 'Data pipeline'],
    links: [],
  },
  {
    slug: 'scannedit',
    name: 'ScannedIt',
    icon: 'scannedit',
    accent: 'gold',
    kind: 'Hackathon',
    event: 'HerSummer Hack (HerCode) · Scandit',
    award: '🥈 2nd place',
    // built with a different team than the others — edit the name once you pick it
    teamPhoto: '/photos/team-scannedit.jpg',
    screenshot: '/photos/shot-scannedit.png',
    tagline: 'An AI shopping concierge that guides you through the store.',
    description:
      'Kitting out for a trip means endless tabs and hunting for staff. Describe what you need in plain language — "lightweight tent for two in the rain" — and Claude reads the whole catalog to build a tailored list. In store, a live aisle map routes you to each item and real Scandit barcode scanning lets you check things off and get head-to-head comparisons on weight, price and warmth.',
    tags: ['React', 'Scandit SDK', 'Claude', 'Django'],
    links: [],
  },
  {
    slug: 'skippre',
    name: 'Skippre',
    icon: 'skippre',
    accent: 'clay',
    kind: 'Product',
    event: 'Marina marketplace',
    screenshot: '/photos/shot-skippre.png',
    tagline: 'An online marketplace for marina berths.',
    description:
      'Skippre is the OTA side of the boating market: skippers search and compare roughly 19,000 marinas — a catalog built from OpenStreetMap — on a clustered map, then enquire directly with operators. Detail pages read live from Supabase; the marina catalog is served fast and statically from the CDN.',
    tags: ['React', 'Supabase', 'Leaflet', 'TypeScript'],
    links: [{ kind: 'live', label: 'skippre.com', url: 'https://skippre.com' }],
  },
  {
    slug: 'docksbase',
    name: 'DocksBase',
    icon: 'docksbase',
    accent: 'sage',
    kind: 'Product',
    event: 'Marina management platform',
    screenshot: '/photos/shot-docksbase.png',
    tagline: 'One operational hub for a whole marina.',
    description:
      'DocksBase is the operator side of the same market: a management platform for berths, reservations, billing, boatyard operations and members. It ships an interactive SVG harbor map, eSignature workflows and a fuel-dock POS — and hands boater bookings off to Skippre through a signed referral integration.',
    tags: ['React', 'Django', 'Stripe', 'PostgreSQL', 'Celery'],
    links: [],
  },
  {
    slug: 'starlit',
    name: 'Starlit',
    icon: 'starlit',
    accent: 'rose',
    kind: 'Personal',
    event: 'Personal project',
    screenshot: '/photos/shot-starlit.png',
    tagline: 'A tiny, gentle daily habit tracker.',
    description:
      'Five little things a day: check one off when you\'ve truly done it, and collect all five for a Five-Star Day. It syncs across devices and installs as a PWA — a small, self-shipped side project I built end to end.',
    tags: ['React', 'Supabase', 'PWA', 'Vite'],
    links: [{ kind: 'live', label: 'Live app', url: 'https://starlit-two.vercel.app' }],
  },
]
